// source: DelineateWorkRequest.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var WorkCheckpoint_pb = require('./WorkCheckpoint_pb.js');
goog.object.extend(proto, WorkCheckpoint_pb);
var WorkPulse_pb = require('./WorkPulse_pb.js');
goog.object.extend(proto, WorkPulse_pb);
goog.exportSymbol('proto.server.DelineateWorkRequest', null, global);
goog.exportSymbol('proto.server.DelineateWorkRequest.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.server.DelineateWorkRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.server.DelineateWorkRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.server.DelineateWorkRequest.displayName = 'proto.server.DelineateWorkRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.server.DelineateWorkRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.server.DelineateWorkRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.server.DelineateWorkRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.server.DelineateWorkRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    checkpoint: (f = msg.getCheckpoint()) && WorkCheckpoint_pb.WorkCheckpoint.toObject(includeInstance, f),
    pulse: (f = msg.getPulse()) && WorkPulse_pb.WorkPulse.toObject(includeInstance, f),
    workkey: jspb.Message.getFieldWithDefault(msg, 4, ""),
    devicekey: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.server.DelineateWorkRequest}
 */
proto.server.DelineateWorkRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.server.DelineateWorkRequest;
  return proto.server.DelineateWorkRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.server.DelineateWorkRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.server.DelineateWorkRequest}
 */
proto.server.DelineateWorkRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.server.DelineateWorkRequest.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new WorkCheckpoint_pb.WorkCheckpoint;
      reader.readMessage(value,WorkCheckpoint_pb.WorkCheckpoint.deserializeBinaryFromReader);
      msg.setCheckpoint(value);
      break;
    case 3:
      var value = new WorkPulse_pb.WorkPulse;
      reader.readMessage(value,WorkPulse_pb.WorkPulse.deserializeBinaryFromReader);
      msg.setPulse(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkkey(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicekey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.server.DelineateWorkRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.server.DelineateWorkRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.server.DelineateWorkRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.server.DelineateWorkRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCheckpoint();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      WorkCheckpoint_pb.WorkCheckpoint.serializeBinaryToWriter
    );
  }
  f = message.getPulse();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      WorkPulse_pb.WorkPulse.serializeBinaryToWriter
    );
  }
  f = message.getWorkkey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDevicekey();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.server.DelineateWorkRequest.Type = {
  PULSE: 0,
  CHECK_POINT: 1
};

/**
 * optional Type type = 1;
 * @return {!proto.server.DelineateWorkRequest.Type}
 */
proto.server.DelineateWorkRequest.prototype.getType = function() {
  return /** @type {!proto.server.DelineateWorkRequest.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.server.DelineateWorkRequest.Type} value
 * @return {!proto.server.DelineateWorkRequest} returns this
 */
proto.server.DelineateWorkRequest.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional work.WorkCheckpoint checkpoint = 2;
 * @return {?proto.work.WorkCheckpoint}
 */
proto.server.DelineateWorkRequest.prototype.getCheckpoint = function() {
  return /** @type{?proto.work.WorkCheckpoint} */ (
    jspb.Message.getWrapperField(this, WorkCheckpoint_pb.WorkCheckpoint, 2));
};


/**
 * @param {?proto.work.WorkCheckpoint|undefined} value
 * @return {!proto.server.DelineateWorkRequest} returns this
*/
proto.server.DelineateWorkRequest.prototype.setCheckpoint = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.server.DelineateWorkRequest} returns this
 */
proto.server.DelineateWorkRequest.prototype.clearCheckpoint = function() {
  return this.setCheckpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.server.DelineateWorkRequest.prototype.hasCheckpoint = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional work.WorkPulse pulse = 3;
 * @return {?proto.work.WorkPulse}
 */
proto.server.DelineateWorkRequest.prototype.getPulse = function() {
  return /** @type{?proto.work.WorkPulse} */ (
    jspb.Message.getWrapperField(this, WorkPulse_pb.WorkPulse, 3));
};


/**
 * @param {?proto.work.WorkPulse|undefined} value
 * @return {!proto.server.DelineateWorkRequest} returns this
*/
proto.server.DelineateWorkRequest.prototype.setPulse = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.server.DelineateWorkRequest} returns this
 */
proto.server.DelineateWorkRequest.prototype.clearPulse = function() {
  return this.setPulse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.server.DelineateWorkRequest.prototype.hasPulse = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string workKey = 4;
 * @return {string}
 */
proto.server.DelineateWorkRequest.prototype.getWorkkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.server.DelineateWorkRequest} returns this
 */
proto.server.DelineateWorkRequest.prototype.setWorkkey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string deviceKey = 5;
 * @return {string}
 */
proto.server.DelineateWorkRequest.prototype.getDevicekey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.server.DelineateWorkRequest} returns this
 */
proto.server.DelineateWorkRequest.prototype.setDevicekey = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


goog.object.extend(exports, proto.server);
