// source: FileIoStats.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.stats.FileIoStats', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stats.FileIoStats = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stats.FileIoStats, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stats.FileIoStats.displayName = 'proto.stats.FileIoStats';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stats.FileIoStats.prototype.toObject = function(opt_includeInstance) {
  return proto.stats.FileIoStats.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stats.FileIoStats} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.FileIoStats.toObject = function(includeInstance, msg) {
  var f, obj = {
    charsreadbytes: jspb.Message.getFieldWithDefault(msg, 1, 0),
    charswritebytes: jspb.Message.getFieldWithDefault(msg, 2, 0),
    numsysreadcalls: jspb.Message.getFieldWithDefault(msg, 3, 0),
    numsyswritecalls: jspb.Message.getFieldWithDefault(msg, 4, 0),
    readbytes: jspb.Message.getFieldWithDefault(msg, 5, 0),
    writebytes: jspb.Message.getFieldWithDefault(msg, 6, 0),
    cancelledwritebytes: jspb.Message.getFieldWithDefault(msg, 7, 0),
    relativetime: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stats.FileIoStats}
 */
proto.stats.FileIoStats.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stats.FileIoStats;
  return proto.stats.FileIoStats.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stats.FileIoStats} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stats.FileIoStats}
 */
proto.stats.FileIoStats.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCharsreadbytes(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCharswritebytes(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumsysreadcalls(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumsyswritecalls(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReadbytes(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWritebytes(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCancelledwritebytes(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRelativetime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stats.FileIoStats.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stats.FileIoStats.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stats.FileIoStats} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.FileIoStats.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCharsreadbytes();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCharswritebytes();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getNumsysreadcalls();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getNumsyswritecalls();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getReadbytes();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getWritebytes();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getCancelledwritebytes();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getRelativetime();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
};


/**
 * optional int64 charsReadBytes = 1;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getCharsreadbytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setCharsreadbytes = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 charsWriteBytes = 2;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getCharswritebytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setCharswritebytes = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 numSysReadCalls = 3;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getNumsysreadcalls = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setNumsysreadcalls = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 numSysWriteCalls = 4;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getNumsyswritecalls = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setNumsyswritecalls = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 readBytes = 5;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getReadbytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setReadbytes = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 writeBytes = 6;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getWritebytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setWritebytes = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 cancelledWriteBytes = 7;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getCancelledwritebytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setCancelledwritebytes = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 relativeTime = 8;
 * @return {number}
 */
proto.stats.FileIoStats.prototype.getRelativetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.FileIoStats} returns this
 */
proto.stats.FileIoStats.prototype.setRelativetime = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


goog.object.extend(exports, proto.stats);
