// source: GetTestPerformanceResponse.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var PerformanceReport_pb = require('./PerformanceReport_pb.js');
goog.object.extend(proto, PerformanceReport_pb);
goog.exportSymbol('proto.server.GetTestPerformanceResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.server.GetTestPerformanceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.server.GetTestPerformanceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.server.GetTestPerformanceResponse.displayName = 'proto.server.GetTestPerformanceResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.server.GetTestPerformanceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.server.GetTestPerformanceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.server.GetTestPerformanceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.server.GetTestPerformanceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    performancereport: (f = msg.getPerformancereport()) && PerformanceReport_pb.PerformanceReport.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.server.GetTestPerformanceResponse}
 */
proto.server.GetTestPerformanceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.server.GetTestPerformanceResponse;
  return proto.server.GetTestPerformanceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.server.GetTestPerformanceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.server.GetTestPerformanceResponse}
 */
proto.server.GetTestPerformanceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new PerformanceReport_pb.PerformanceReport;
      reader.readMessage(value,PerformanceReport_pb.PerformanceReport.deserializeBinaryFromReader);
      msg.setPerformancereport(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.server.GetTestPerformanceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.server.GetTestPerformanceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.server.GetTestPerformanceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.server.GetTestPerformanceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPerformancereport();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      PerformanceReport_pb.PerformanceReport.serializeBinaryToWriter
    );
  }
};


/**
 * optional reports.PerformanceReport performanceReport = 1;
 * @return {?proto.reports.PerformanceReport}
 */
proto.server.GetTestPerformanceResponse.prototype.getPerformancereport = function() {
  return /** @type{?proto.reports.PerformanceReport} */ (
    jspb.Message.getWrapperField(this, PerformanceReport_pb.PerformanceReport, 1));
};


/**
 * @param {?proto.reports.PerformanceReport|undefined} value
 * @return {!proto.server.GetTestPerformanceResponse} returns this
*/
proto.server.GetTestPerformanceResponse.prototype.setPerformancereport = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.server.GetTestPerformanceResponse} returns this
 */
proto.server.GetTestPerformanceResponse.prototype.clearPerformancereport = function() {
  return this.setPerformancereport(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.server.GetTestPerformanceResponse.prototype.hasPerformancereport = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.server);
