// source: HardwareProperties.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.device.HardwareProperties', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.device.HardwareProperties = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.device.HardwareProperties.repeatedFields_, null);
};
goog.inherits(proto.device.HardwareProperties, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.device.HardwareProperties.displayName = 'proto.device.HardwareProperties';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.device.HardwareProperties.repeatedFields_ = [10,11,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.device.HardwareProperties.prototype.toObject = function(opt_includeInstance) {
  return proto.device.HardwareProperties.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.device.HardwareProperties} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.device.HardwareProperties.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: jspb.Message.getFieldWithDefault(msg, 1, ""),
    device: jspb.Message.getFieldWithDefault(msg, 2, ""),
    board: jspb.Message.getFieldWithDefault(msg, 3, ""),
    manufacturer: jspb.Message.getFieldWithDefault(msg, 4, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 5, ""),
    model: jspb.Message.getFieldWithDefault(msg, 6, ""),
    bootloader: jspb.Message.getFieldWithDefault(msg, 7, ""),
    hardware: jspb.Message.getFieldWithDefault(msg, 8, ""),
    supportedabisList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    supported32bitabisList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    supported64bitabisList: (f = jspb.Message.getRepeatedField(msg, 12)) == null ? undefined : f,
    radioversion: jspb.Message.getFieldWithDefault(msg, 13, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.device.HardwareProperties}
 */
proto.device.HardwareProperties.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.device.HardwareProperties;
  return proto.device.HardwareProperties.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.device.HardwareProperties} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.device.HardwareProperties}
 */
proto.device.HardwareProperties.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProduct(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevice(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBoard(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setManufacturer(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setModel(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setBootloader(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setHardware(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addSupportedabis(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addSupported32bitabis(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.addSupported64bitabis(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setRadioversion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.device.HardwareProperties.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.device.HardwareProperties.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.device.HardwareProperties} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.device.HardwareProperties.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDevice();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBoard();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getManufacturer();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getModel();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getBootloader();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getHardware();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSupportedabisList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getSupported32bitabisList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getSupported64bitabisList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      12,
      f
    );
  }
  f = message.getRadioversion();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
};


/**
 * optional string product = 1;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getProduct = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setProduct = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string device = 2;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getDevice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setDevice = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string board = 3;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getBoard = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setBoard = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string manufacturer = 4;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getManufacturer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setManufacturer = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string brand = 5;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string model = 6;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setModel = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string bootloader = 7;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getBootloader = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setBootloader = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string hardware = 8;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getHardware = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setHardware = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * repeated string supportedAbis = 10;
 * @return {!Array<string>}
 */
proto.device.HardwareProperties.prototype.getSupportedabisList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setSupportedabisList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.addSupportedabis = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.clearSupportedabisList = function() {
  return this.setSupportedabisList([]);
};


/**
 * repeated string supported32BitAbis = 11;
 * @return {!Array<string>}
 */
proto.device.HardwareProperties.prototype.getSupported32bitabisList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setSupported32bitabisList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.addSupported32bitabis = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.clearSupported32bitabisList = function() {
  return this.setSupported32bitabisList([]);
};


/**
 * repeated string supported64BitAbis = 12;
 * @return {!Array<string>}
 */
proto.device.HardwareProperties.prototype.getSupported64bitabisList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 12));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setSupported64bitabisList = function(value) {
  return jspb.Message.setField(this, 12, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.addSupported64bitabis = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 12, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.clearSupported64bitabisList = function() {
  return this.setSupported64bitabisList([]);
};


/**
 * optional string radioVersion = 13;
 * @return {string}
 */
proto.device.HardwareProperties.prototype.getRadioversion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.HardwareProperties} returns this
 */
proto.device.HardwareProperties.prototype.setRadioversion = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


goog.object.extend(exports, proto.device);
