// source: OsProperties.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.device.OsProperties', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.device.OsProperties = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.device.OsProperties, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.device.OsProperties.displayName = 'proto.device.OsProperties';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.device.OsProperties.prototype.toObject = function(opt_includeInstance) {
  return proto.device.OsProperties.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.device.OsProperties} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.device.OsProperties.toObject = function(includeInstance, msg) {
  var f, obj = {
    sdknumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    previewsdknumber: jspb.Message.getFieldWithDefault(msg, 2, 0),
    securitypatch: jspb.Message.getFieldWithDefault(msg, 3, ""),
    incremental: jspb.Message.getFieldWithDefault(msg, 4, ""),
    codename: jspb.Message.getFieldWithDefault(msg, 5, ""),
    release: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.device.OsProperties}
 */
proto.device.OsProperties.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.device.OsProperties;
  return proto.device.OsProperties.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.device.OsProperties} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.device.OsProperties}
 */
proto.device.OsProperties.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSdknumber(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPreviewsdknumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecuritypatch(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setIncremental(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCodename(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRelease(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.device.OsProperties.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.device.OsProperties.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.device.OsProperties} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.device.OsProperties.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSdknumber();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getPreviewsdknumber();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSecuritypatch();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIncremental();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCodename();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRelease();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional int32 sdkNumber = 1;
 * @return {number}
 */
proto.device.OsProperties.prototype.getSdknumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.device.OsProperties} returns this
 */
proto.device.OsProperties.prototype.setSdknumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 previewSdkNumber = 2;
 * @return {number}
 */
proto.device.OsProperties.prototype.getPreviewsdknumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.device.OsProperties} returns this
 */
proto.device.OsProperties.prototype.setPreviewsdknumber = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string securityPatch = 3;
 * @return {string}
 */
proto.device.OsProperties.prototype.getSecuritypatch = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.OsProperties} returns this
 */
proto.device.OsProperties.prototype.setSecuritypatch = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string incremental = 4;
 * @return {string}
 */
proto.device.OsProperties.prototype.getIncremental = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.OsProperties} returns this
 */
proto.device.OsProperties.prototype.setIncremental = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string codeName = 5;
 * @return {string}
 */
proto.device.OsProperties.prototype.getCodename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.OsProperties} returns this
 */
proto.device.OsProperties.prototype.setCodename = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string release = 6;
 * @return {string}
 */
proto.device.OsProperties.prototype.getRelease = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.device.OsProperties} returns this
 */
proto.device.OsProperties.prototype.setRelease = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.device);
