// source: PerformanceReport.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var BinderStats_pb = require('./BinderStats_pb.js');
goog.object.extend(proto, BinderStats_pb);
var FileIoStats_pb = require('./FileIoStats_pb.js');
goog.object.extend(proto, FileIoStats_pb);
var ThreadStats_pb = require('./ThreadStats_pb.js');
goog.object.extend(proto, ThreadStats_pb);
var GcStats_pb = require('./GcStats_pb.js');
goog.object.extend(proto, GcStats_pb);
var UnixProcessStats_pb = require('./UnixProcessStats_pb.js');
goog.object.extend(proto, UnixProcessStats_pb);
var MemoryStats_pb = require('./MemoryStats_pb.js');
goog.object.extend(proto, MemoryStats_pb);
var TestSummaryProfile_pb = require('./TestSummaryProfile_pb.js');
goog.object.extend(proto, TestSummaryProfile_pb);
var NetworkStats_pb = require('./NetworkStats_pb.js');
goog.object.extend(proto, NetworkStats_pb);
var FrameStats_pb = require('./FrameStats_pb.js');
goog.object.extend(proto, FrameStats_pb);
goog.exportSymbol('proto.reports.PerformanceReport', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reports.PerformanceReport = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reports.PerformanceReport.repeatedFields_, null);
};
goog.inherits(proto.reports.PerformanceReport, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reports.PerformanceReport.displayName = 'proto.reports.PerformanceReport';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reports.PerformanceReport.repeatedFields_ = [1,2,3,4,5,6,7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reports.PerformanceReport.prototype.toObject = function(opt_includeInstance) {
  return proto.reports.PerformanceReport.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reports.PerformanceReport} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reports.PerformanceReport.toObject = function(includeInstance, msg) {
  var f, obj = {
    memorystatsList: jspb.Message.toObjectList(msg.getMemorystatsList(),
    MemoryStats_pb.MemoryStats.toObject, includeInstance),
    binderstatsList: jspb.Message.toObjectList(msg.getBinderstatsList(),
    BinderStats_pb.BinderStats.toObject, includeInstance),
    fileiostatsList: jspb.Message.toObjectList(msg.getFileiostatsList(),
    FileIoStats_pb.FileIoStats.toObject, includeInstance),
    threadstatsList: jspb.Message.toObjectList(msg.getThreadstatsList(),
    ThreadStats_pb.ThreadStats.toObject, includeInstance),
    gcstatsList: jspb.Message.toObjectList(msg.getGcstatsList(),
    GcStats_pb.GcStats.toObject, includeInstance),
    unixprocessstatsList: jspb.Message.toObjectList(msg.getUnixprocessstatsList(),
    UnixProcessStats_pb.UnixProcessStats.toObject, includeInstance),
    networkstatsList: jspb.Message.toObjectList(msg.getNetworkstatsList(),
    NetworkStats_pb.NetworkStats.toObject, includeInstance),
    framestatsList: jspb.Message.toObjectList(msg.getFramestatsList(),
    FrameStats_pb.FrameStats.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reports.PerformanceReport}
 */
proto.reports.PerformanceReport.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reports.PerformanceReport;
  return proto.reports.PerformanceReport.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reports.PerformanceReport} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reports.PerformanceReport}
 */
proto.reports.PerformanceReport.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new MemoryStats_pb.MemoryStats;
      reader.readMessage(value,MemoryStats_pb.MemoryStats.deserializeBinaryFromReader);
      msg.addMemorystats(value);
      break;
    case 2:
      var value = new BinderStats_pb.BinderStats;
      reader.readMessage(value,BinderStats_pb.BinderStats.deserializeBinaryFromReader);
      msg.addBinderstats(value);
      break;
    case 3:
      var value = new FileIoStats_pb.FileIoStats;
      reader.readMessage(value,FileIoStats_pb.FileIoStats.deserializeBinaryFromReader);
      msg.addFileiostats(value);
      break;
    case 4:
      var value = new ThreadStats_pb.ThreadStats;
      reader.readMessage(value,ThreadStats_pb.ThreadStats.deserializeBinaryFromReader);
      msg.addThreadstats(value);
      break;
    case 5:
      var value = new GcStats_pb.GcStats;
      reader.readMessage(value,GcStats_pb.GcStats.deserializeBinaryFromReader);
      msg.addGcstats(value);
      break;
    case 6:
      var value = new UnixProcessStats_pb.UnixProcessStats;
      reader.readMessage(value,UnixProcessStats_pb.UnixProcessStats.deserializeBinaryFromReader);
      msg.addUnixprocessstats(value);
      break;
    case 7:
      var value = new NetworkStats_pb.NetworkStats;
      reader.readMessage(value,NetworkStats_pb.NetworkStats.deserializeBinaryFromReader);
      msg.addNetworkstats(value);
      break;
    case 8:
      var value = new FrameStats_pb.FrameStats;
      reader.readMessage(value,FrameStats_pb.FrameStats.deserializeBinaryFromReader);
      msg.addFramestats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reports.PerformanceReport.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reports.PerformanceReport.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reports.PerformanceReport} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reports.PerformanceReport.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMemorystatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      MemoryStats_pb.MemoryStats.serializeBinaryToWriter
    );
  }
  f = message.getBinderstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      BinderStats_pb.BinderStats.serializeBinaryToWriter
    );
  }
  f = message.getFileiostatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      FileIoStats_pb.FileIoStats.serializeBinaryToWriter
    );
  }
  f = message.getThreadstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      ThreadStats_pb.ThreadStats.serializeBinaryToWriter
    );
  }
  f = message.getGcstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      GcStats_pb.GcStats.serializeBinaryToWriter
    );
  }
  f = message.getUnixprocessstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      UnixProcessStats_pb.UnixProcessStats.serializeBinaryToWriter
    );
  }
  f = message.getNetworkstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      NetworkStats_pb.NetworkStats.serializeBinaryToWriter
    );
  }
  f = message.getFramestatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      FrameStats_pb.FrameStats.serializeBinaryToWriter
    );
  }
};


/**
 * repeated stats.MemoryStats memoryStats = 1;
 * @return {!Array<!proto.stats.MemoryStats>}
 */
proto.reports.PerformanceReport.prototype.getMemorystatsList = function() {
  return /** @type{!Array<!proto.stats.MemoryStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, MemoryStats_pb.MemoryStats, 1));
};


/**
 * @param {!Array<!proto.stats.MemoryStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setMemorystatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.stats.MemoryStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.MemoryStats}
 */
proto.reports.PerformanceReport.prototype.addMemorystats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.stats.MemoryStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearMemorystatsList = function() {
  return this.setMemorystatsList([]);
};


/**
 * repeated stats.BinderStats binderStats = 2;
 * @return {!Array<!proto.stats.BinderStats>}
 */
proto.reports.PerformanceReport.prototype.getBinderstatsList = function() {
  return /** @type{!Array<!proto.stats.BinderStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, BinderStats_pb.BinderStats, 2));
};


/**
 * @param {!Array<!proto.stats.BinderStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setBinderstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.stats.BinderStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.BinderStats}
 */
proto.reports.PerformanceReport.prototype.addBinderstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.stats.BinderStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearBinderstatsList = function() {
  return this.setBinderstatsList([]);
};


/**
 * repeated stats.FileIoStats fileIoStats = 3;
 * @return {!Array<!proto.stats.FileIoStats>}
 */
proto.reports.PerformanceReport.prototype.getFileiostatsList = function() {
  return /** @type{!Array<!proto.stats.FileIoStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, FileIoStats_pb.FileIoStats, 3));
};


/**
 * @param {!Array<!proto.stats.FileIoStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setFileiostatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.stats.FileIoStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.FileIoStats}
 */
proto.reports.PerformanceReport.prototype.addFileiostats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.stats.FileIoStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearFileiostatsList = function() {
  return this.setFileiostatsList([]);
};


/**
 * repeated stats.ThreadStats threadStats = 4;
 * @return {!Array<!proto.stats.ThreadStats>}
 */
proto.reports.PerformanceReport.prototype.getThreadstatsList = function() {
  return /** @type{!Array<!proto.stats.ThreadStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, ThreadStats_pb.ThreadStats, 4));
};


/**
 * @param {!Array<!proto.stats.ThreadStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setThreadstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.stats.ThreadStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.ThreadStats}
 */
proto.reports.PerformanceReport.prototype.addThreadstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.stats.ThreadStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearThreadstatsList = function() {
  return this.setThreadstatsList([]);
};


/**
 * repeated stats.GcStats gcStats = 5;
 * @return {!Array<!proto.stats.GcStats>}
 */
proto.reports.PerformanceReport.prototype.getGcstatsList = function() {
  return /** @type{!Array<!proto.stats.GcStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, GcStats_pb.GcStats, 5));
};


/**
 * @param {!Array<!proto.stats.GcStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setGcstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.stats.GcStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.GcStats}
 */
proto.reports.PerformanceReport.prototype.addGcstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.stats.GcStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearGcstatsList = function() {
  return this.setGcstatsList([]);
};


/**
 * repeated stats.UnixProcessStats unixProcessStats = 6;
 * @return {!Array<!proto.stats.UnixProcessStats>}
 */
proto.reports.PerformanceReport.prototype.getUnixprocessstatsList = function() {
  return /** @type{!Array<!proto.stats.UnixProcessStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, UnixProcessStats_pb.UnixProcessStats, 6));
};


/**
 * @param {!Array<!proto.stats.UnixProcessStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setUnixprocessstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.stats.UnixProcessStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.UnixProcessStats}
 */
proto.reports.PerformanceReport.prototype.addUnixprocessstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.stats.UnixProcessStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearUnixprocessstatsList = function() {
  return this.setUnixprocessstatsList([]);
};


/**
 * repeated stats.NetworkStats networkStats = 7;
 * @return {!Array<!proto.stats.NetworkStats>}
 */
proto.reports.PerformanceReport.prototype.getNetworkstatsList = function() {
  return /** @type{!Array<!proto.stats.NetworkStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, NetworkStats_pb.NetworkStats, 7));
};


/**
 * @param {!Array<!proto.stats.NetworkStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setNetworkstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.stats.NetworkStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.NetworkStats}
 */
proto.reports.PerformanceReport.prototype.addNetworkstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.stats.NetworkStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearNetworkstatsList = function() {
  return this.setNetworkstatsList([]);
};


/**
 * repeated stats.FrameStats frameStats = 8;
 * @return {!Array<!proto.stats.FrameStats>}
 */
proto.reports.PerformanceReport.prototype.getFramestatsList = function() {
  return /** @type{!Array<!proto.stats.FrameStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, FrameStats_pb.FrameStats, 8));
};


/**
 * @param {!Array<!proto.stats.FrameStats>} value
 * @return {!proto.reports.PerformanceReport} returns this
*/
proto.reports.PerformanceReport.prototype.setFramestatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.stats.FrameStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.FrameStats}
 */
proto.reports.PerformanceReport.prototype.addFramestats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.stats.FrameStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.PerformanceReport} returns this
 */
proto.reports.PerformanceReport.prototype.clearFramestatsList = function() {
  return this.setFramestatsList([]);
};


goog.object.extend(exports, proto.reports);
