// source: ProcessStats.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.stats.ProcessStats', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stats.ProcessStats = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.stats.ProcessStats.repeatedFields_, null);
};
goog.inherits(proto.stats.ProcessStats, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stats.ProcessStats.displayName = 'proto.stats.ProcessStats';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.stats.ProcessStats.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stats.ProcessStats.prototype.toObject = function(opt_includeInstance) {
  return proto.stats.ProcessStats.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stats.ProcessStats} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.ProcessStats.toObject = function(includeInstance, msg) {
  var f, obj = {
    pid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    uid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    exclusivecoresList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    startelapsedrealtime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    startuptimemillis: jspb.Message.getFieldWithDefault(msg, 5, 0),
    is64bit: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stats.ProcessStats}
 */
proto.stats.ProcessStats.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stats.ProcessStats;
  return proto.stats.ProcessStats.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stats.ProcessStats} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stats.ProcessStats}
 */
proto.stats.ProcessStats.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUid(value);
      break;
    case 3:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setExclusivecoresList(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartelapsedrealtime(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartuptimemillis(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIs64bit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stats.ProcessStats.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stats.ProcessStats.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stats.ProcessStats} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.ProcessStats.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getUid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getExclusivecoresList();
  if (f.length > 0) {
    writer.writePackedInt32(
      3,
      f
    );
  }
  f = message.getStartelapsedrealtime();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getStartuptimemillis();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getIs64bit();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional int32 pid = 1;
 * @return {number}
 */
proto.stats.ProcessStats.prototype.getPid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.setPid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 uid = 2;
 * @return {number}
 */
proto.stats.ProcessStats.prototype.getUid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.setUid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated int32 exclusiveCores = 3;
 * @return {!Array<number>}
 */
proto.stats.ProcessStats.prototype.getExclusivecoresList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.setExclusivecoresList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.addExclusivecores = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.clearExclusivecoresList = function() {
  return this.setExclusivecoresList([]);
};


/**
 * optional int64 startElapsedRealtime = 4;
 * @return {number}
 */
proto.stats.ProcessStats.prototype.getStartelapsedrealtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.setStartelapsedrealtime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 startUptimeMillis = 5;
 * @return {number}
 */
proto.stats.ProcessStats.prototype.getStartuptimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.setStartuptimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional bool is64Bit = 6;
 * @return {boolean}
 */
proto.stats.ProcessStats.prototype.getIs64bit = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.stats.ProcessStats} returns this
 */
proto.stats.ProcessStats.prototype.setIs64bit = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


goog.object.extend(exports, proto.stats);
