// source: ResourceUsageStats.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.stats.ResourceUsageStats', null, global);
goog.exportSymbol('proto.stats.ResourceUsageStats.Timer', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stats.ResourceUsageStats = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stats.ResourceUsageStats, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stats.ResourceUsageStats.displayName = 'proto.stats.ResourceUsageStats';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stats.ResourceUsageStats.Timer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.stats.ResourceUsageStats.Timer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stats.ResourceUsageStats.Timer.displayName = 'proto.stats.ResourceUsageStats.Timer';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stats.ResourceUsageStats.prototype.toObject = function(opt_includeInstance) {
  return proto.stats.ResourceUsageStats.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stats.ResourceUsageStats} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.ResourceUsageStats.toObject = function(includeInstance, msg) {
  var f, obj = {
    audiocount: jspb.Message.getFieldWithDefault(msg, 1, 0),
    audiotimemillis: jspb.Message.getFieldWithDefault(msg, 2, 0),
    videocount: jspb.Message.getFieldWithDefault(msg, 3, 0),
    videotimemillis: jspb.Message.getFieldWithDefault(msg, 4, 0),
    vibratorcount: jspb.Message.getFieldWithDefault(msg, 5, 0),
    vibratortimemillis: jspb.Message.getFieldWithDefault(msg, 6, 0),
    gpssensorcount: jspb.Message.getFieldWithDefault(msg, 7, 0),
    gpssensortimemillis: jspb.Message.getFieldWithDefault(msg, 8, 0),
    bluetoothcount: jspb.Message.getFieldWithDefault(msg, 9, 0),
    bluetoothtimemillis: jspb.Message.getFieldWithDefault(msg, 10, 0),
    cameracount: jspb.Message.getFieldWithDefault(msg, 11, 0),
    cameratimemillis: jspb.Message.getFieldWithDefault(msg, 12, 0),
    flashlightcount: jspb.Message.getFieldWithDefault(msg, 13, 0),
    flashlighttimemillis: jspb.Message.getFieldWithDefault(msg, 14, 0),
    wifiscancount: jspb.Message.getFieldWithDefault(msg, 15, 0),
    wifiscantimemillis: jspb.Message.getFieldWithDefault(msg, 16, 0),
    mobileradioactivecount: jspb.Message.getFieldWithDefault(msg, 17, 0),
    mobileradioactivetimemillis: jspb.Message.getFieldWithDefault(msg, 18, 0),
    wifimulticastmillis: jspb.Message.getFieldWithDefault(msg, 19, 0),
    bluetoothrxbytes: jspb.Message.getFieldWithDefault(msg, 20, 0),
    bluetoothtxbytes: jspb.Message.getFieldWithDefault(msg, 21, 0),
    bluetoothrxpackets: jspb.Message.getFieldWithDefault(msg, 22, 0),
    bluetoothtxpackets: jspb.Message.getFieldWithDefault(msg, 23, 0),
    wifiidlemillis: jspb.Message.getFieldWithDefault(msg, 31, 0),
    bluetoothidlemillis: jspb.Message.getFieldWithDefault(msg, 33, 0),
    mobileidlemillis: jspb.Message.getFieldWithDefault(msg, 35, 0),
    wifipowermams: jspb.Message.getFieldWithDefault(msg, 32, 0),
    bluetoothpowermams: jspb.Message.getFieldWithDefault(msg, 34, 0),
    mobilepowermams: jspb.Message.getFieldWithDefault(msg, 36, 0),
    wifirunningms: jspb.Message.getFieldWithDefault(msg, 37, 0),
    wififulllockms: jspb.Message.getFieldWithDefault(msg, 38, 0),
    jobsMap: (f = msg.getJobsMap()) ? f.toObject(includeInstance, proto.stats.ResourceUsageStats.Timer.toObject) : [],
    sensorsMap: (f = msg.getSensorsMap()) ? f.toObject(includeInstance, proto.stats.ResourceUsageStats.Timer.toObject) : [],
    syncsMap: (f = msg.getSyncsMap()) ? f.toObject(includeInstance, proto.stats.ResourceUsageStats.Timer.toObject) : [],
    wakelocksdrawMap: (f = msg.getWakelocksdrawMap()) ? f.toObject(includeInstance, proto.stats.ResourceUsageStats.Timer.toObject) : [],
    wakelocksfullMap: (f = msg.getWakelocksfullMap()) ? f.toObject(includeInstance, proto.stats.ResourceUsageStats.Timer.toObject) : [],
    wakelockspartialMap: (f = msg.getWakelockspartialMap()) ? f.toObject(includeInstance, proto.stats.ResourceUsageStats.Timer.toObject) : [],
    wakelockswindowMap: (f = msg.getWakelockswindowMap()) ? f.toObject(includeInstance, proto.stats.ResourceUsageStats.Timer.toObject) : [],
    relativetime: jspb.Message.getFieldWithDefault(msg, 39, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stats.ResourceUsageStats}
 */
proto.stats.ResourceUsageStats.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stats.ResourceUsageStats;
  return proto.stats.ResourceUsageStats.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stats.ResourceUsageStats} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stats.ResourceUsageStats}
 */
proto.stats.ResourceUsageStats.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAudiocount(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAudiotimemillis(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVideocount(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVideotimemillis(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVibratorcount(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVibratortimemillis(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGpssensorcount(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setGpssensortimemillis(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBluetoothcount(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluetoothtimemillis(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCameracount(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCameratimemillis(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFlashlightcount(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFlashlighttimemillis(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWifiscancount(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWifiscantimemillis(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMobileradioactivecount(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMobileradioactivetimemillis(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWifimulticastmillis(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluetoothrxbytes(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluetoothtxbytes(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluetoothrxpackets(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluetoothtxpackets(value);
      break;
    case 31:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWifiidlemillis(value);
      break;
    case 33:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluetoothidlemillis(value);
      break;
    case 35:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMobileidlemillis(value);
      break;
    case 32:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWifipowermams(value);
      break;
    case 34:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBluetoothpowermams(value);
      break;
    case 36:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMobilepowermams(value);
      break;
    case 37:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWifirunningms(value);
      break;
    case 38:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setWififulllockms(value);
      break;
    case 24:
      var value = msg.getJobsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader, "", new proto.stats.ResourceUsageStats.Timer());
         });
      break;
    case 25:
      var value = msg.getSensorsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader, "", new proto.stats.ResourceUsageStats.Timer());
         });
      break;
    case 26:
      var value = msg.getSyncsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader, "", new proto.stats.ResourceUsageStats.Timer());
         });
      break;
    case 27:
      var value = msg.getWakelocksdrawMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader, "", new proto.stats.ResourceUsageStats.Timer());
         });
      break;
    case 28:
      var value = msg.getWakelocksfullMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader, "", new proto.stats.ResourceUsageStats.Timer());
         });
      break;
    case 29:
      var value = msg.getWakelockspartialMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader, "", new proto.stats.ResourceUsageStats.Timer());
         });
      break;
    case 30:
      var value = msg.getWakelockswindowMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader, "", new proto.stats.ResourceUsageStats.Timer());
         });
      break;
    case 39:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRelativetime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stats.ResourceUsageStats.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stats.ResourceUsageStats.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stats.ResourceUsageStats} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.ResourceUsageStats.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAudiocount();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAudiotimemillis();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getVideocount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getVideotimemillis();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getVibratorcount();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getVibratortimemillis();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getGpssensorcount();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getGpssensortimemillis();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getBluetoothcount();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getBluetoothtimemillis();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getCameracount();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getCameratimemillis();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getFlashlightcount();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getFlashlighttimemillis();
  if (f !== 0) {
    writer.writeInt64(
      14,
      f
    );
  }
  f = message.getWifiscancount();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getWifiscantimemillis();
  if (f !== 0) {
    writer.writeInt64(
      16,
      f
    );
  }
  f = message.getMobileradioactivecount();
  if (f !== 0) {
    writer.writeInt32(
      17,
      f
    );
  }
  f = message.getMobileradioactivetimemillis();
  if (f !== 0) {
    writer.writeInt64(
      18,
      f
    );
  }
  f = message.getWifimulticastmillis();
  if (f !== 0) {
    writer.writeInt64(
      19,
      f
    );
  }
  f = message.getBluetoothrxbytes();
  if (f !== 0) {
    writer.writeInt64(
      20,
      f
    );
  }
  f = message.getBluetoothtxbytes();
  if (f !== 0) {
    writer.writeInt64(
      21,
      f
    );
  }
  f = message.getBluetoothrxpackets();
  if (f !== 0) {
    writer.writeInt64(
      22,
      f
    );
  }
  f = message.getBluetoothtxpackets();
  if (f !== 0) {
    writer.writeInt64(
      23,
      f
    );
  }
  f = message.getWifiidlemillis();
  if (f !== 0) {
    writer.writeInt64(
      31,
      f
    );
  }
  f = message.getBluetoothidlemillis();
  if (f !== 0) {
    writer.writeInt64(
      33,
      f
    );
  }
  f = message.getMobileidlemillis();
  if (f !== 0) {
    writer.writeInt64(
      35,
      f
    );
  }
  f = message.getWifipowermams();
  if (f !== 0) {
    writer.writeInt64(
      32,
      f
    );
  }
  f = message.getBluetoothpowermams();
  if (f !== 0) {
    writer.writeInt64(
      34,
      f
    );
  }
  f = message.getMobilepowermams();
  if (f !== 0) {
    writer.writeInt64(
      36,
      f
    );
  }
  f = message.getWifirunningms();
  if (f !== 0) {
    writer.writeInt64(
      37,
      f
    );
  }
  f = message.getWififulllockms();
  if (f !== 0) {
    writer.writeInt64(
      38,
      f
    );
  }
  f = message.getJobsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(24, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter);
  }
  f = message.getSensorsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(25, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter);
  }
  f = message.getSyncsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(26, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter);
  }
  f = message.getWakelocksdrawMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(27, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter);
  }
  f = message.getWakelocksfullMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(28, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter);
  }
  f = message.getWakelockspartialMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(29, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter);
  }
  f = message.getWakelockswindowMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(30, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter);
  }
  f = message.getRelativetime();
  if (f !== 0) {
    writer.writeInt32(
      39,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stats.ResourceUsageStats.Timer.prototype.toObject = function(opt_includeInstance) {
  return proto.stats.ResourceUsageStats.Timer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stats.ResourceUsageStats.Timer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.ResourceUsageStats.Timer.toObject = function(includeInstance, msg) {
  var f, obj = {
    count: jspb.Message.getFieldWithDefault(msg, 1, 0),
    timemillis: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stats.ResourceUsageStats.Timer}
 */
proto.stats.ResourceUsageStats.Timer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stats.ResourceUsageStats.Timer;
  return proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stats.ResourceUsageStats.Timer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stats.ResourceUsageStats.Timer}
 */
proto.stats.ResourceUsageStats.Timer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimemillis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stats.ResourceUsageStats.Timer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stats.ResourceUsageStats.Timer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.ResourceUsageStats.Timer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTimemillis();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional int32 count = 1;
 * @return {number}
 */
proto.stats.ResourceUsageStats.Timer.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats.Timer} returns this
 */
proto.stats.ResourceUsageStats.Timer.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 timeMillis = 2;
 * @return {number}
 */
proto.stats.ResourceUsageStats.Timer.prototype.getTimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats.Timer} returns this
 */
proto.stats.ResourceUsageStats.Timer.prototype.setTimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 audioCount = 1;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getAudiocount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setAudiocount = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 audioTimeMillis = 2;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getAudiotimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setAudiotimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 videoCount = 3;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getVideocount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setVideocount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 videoTimeMillis = 4;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getVideotimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setVideotimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 vibratorCount = 5;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getVibratorcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setVibratorcount = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 vibratorTimeMillis = 6;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getVibratortimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setVibratortimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 gpsSensorCount = 7;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getGpssensorcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setGpssensorcount = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 gpsSensorTimeMillis = 8;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getGpssensortimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setGpssensortimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 bluetoothCount = 9;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothcount = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 bluetoothTimeMillis = 10;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothtimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothtimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 cameraCount = 11;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getCameracount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setCameracount = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int64 cameraTimeMillis = 12;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getCameratimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setCameratimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 flashlightCount = 13;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getFlashlightcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setFlashlightcount = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int64 flashlightTimeMillis = 14;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getFlashlighttimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setFlashlighttimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 wifiScanCount = 15;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getWifiscancount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setWifiscancount = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional int64 wifiScanTimeMillis = 16;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getWifiscantimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setWifiscantimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional int32 mobileRadioActiveCount = 17;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getMobileradioactivecount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setMobileradioactivecount = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional int64 mobileRadioActiveTimeMillis = 18;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getMobileradioactivetimemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setMobileradioactivetimemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional int64 wifiMultiCastMillis = 19;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getWifimulticastmillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setWifimulticastmillis = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional int64 bluetoothRxBytes = 20;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothrxbytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothrxbytes = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional int64 bluetoothTxBytes = 21;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothtxbytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothtxbytes = function(value) {
  return jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional int64 bluetoothRxPackets = 22;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothrxpackets = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothrxpackets = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional int64 bluetoothTxPackets = 23;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothtxpackets = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothtxpackets = function(value) {
  return jspb.Message.setProto3IntField(this, 23, value);
};


/**
 * optional int64 wifiIdleMillis = 31;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getWifiidlemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 31, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setWifiidlemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 31, value);
};


/**
 * optional int64 bluetoothIdleMillis = 33;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothidlemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 33, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothidlemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 33, value);
};


/**
 * optional int64 mobileIdleMillis = 35;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getMobileidlemillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 35, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setMobileidlemillis = function(value) {
  return jspb.Message.setProto3IntField(this, 35, value);
};


/**
 * optional int64 wifiPowerMams = 32;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getWifipowermams = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 32, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setWifipowermams = function(value) {
  return jspb.Message.setProto3IntField(this, 32, value);
};


/**
 * optional int64 bluetoothPowerMams = 34;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getBluetoothpowermams = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 34, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setBluetoothpowermams = function(value) {
  return jspb.Message.setProto3IntField(this, 34, value);
};


/**
 * optional int64 mobilePowerMams = 36;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getMobilepowermams = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 36, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setMobilepowermams = function(value) {
  return jspb.Message.setProto3IntField(this, 36, value);
};


/**
 * optional int64 wifiRunningMs = 37;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getWifirunningms = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 37, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setWifirunningms = function(value) {
  return jspb.Message.setProto3IntField(this, 37, value);
};


/**
 * optional int64 wifiFullLockMs = 38;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getWififulllockms = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 38, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setWififulllockms = function(value) {
  return jspb.Message.setProto3IntField(this, 38, value);
};


/**
 * map<string, Timer> jobs = 24;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>}
 */
proto.stats.ResourceUsageStats.prototype.getJobsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>} */ (
      jspb.Message.getMapField(this, 24, opt_noLazyCreate,
      proto.stats.ResourceUsageStats.Timer));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.clearJobsMap = function() {
  this.getJobsMap().clear();
  return this;};


/**
 * map<string, Timer> sensors = 25;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>}
 */
proto.stats.ResourceUsageStats.prototype.getSensorsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>} */ (
      jspb.Message.getMapField(this, 25, opt_noLazyCreate,
      proto.stats.ResourceUsageStats.Timer));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.clearSensorsMap = function() {
  this.getSensorsMap().clear();
  return this;};


/**
 * map<string, Timer> syncs = 26;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>}
 */
proto.stats.ResourceUsageStats.prototype.getSyncsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>} */ (
      jspb.Message.getMapField(this, 26, opt_noLazyCreate,
      proto.stats.ResourceUsageStats.Timer));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.clearSyncsMap = function() {
  this.getSyncsMap().clear();
  return this;};


/**
 * map<string, Timer> wakeLocksDraw = 27;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>}
 */
proto.stats.ResourceUsageStats.prototype.getWakelocksdrawMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>} */ (
      jspb.Message.getMapField(this, 27, opt_noLazyCreate,
      proto.stats.ResourceUsageStats.Timer));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.clearWakelocksdrawMap = function() {
  this.getWakelocksdrawMap().clear();
  return this;};


/**
 * map<string, Timer> wakeLocksFull = 28;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>}
 */
proto.stats.ResourceUsageStats.prototype.getWakelocksfullMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>} */ (
      jspb.Message.getMapField(this, 28, opt_noLazyCreate,
      proto.stats.ResourceUsageStats.Timer));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.clearWakelocksfullMap = function() {
  this.getWakelocksfullMap().clear();
  return this;};


/**
 * map<string, Timer> wakeLocksPartial = 29;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>}
 */
proto.stats.ResourceUsageStats.prototype.getWakelockspartialMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>} */ (
      jspb.Message.getMapField(this, 29, opt_noLazyCreate,
      proto.stats.ResourceUsageStats.Timer));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.clearWakelockspartialMap = function() {
  this.getWakelockspartialMap().clear();
  return this;};


/**
 * map<string, Timer> wakeLocksWindow = 30;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>}
 */
proto.stats.ResourceUsageStats.prototype.getWakelockswindowMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.stats.ResourceUsageStats.Timer>} */ (
      jspb.Message.getMapField(this, 30, opt_noLazyCreate,
      proto.stats.ResourceUsageStats.Timer));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.clearWakelockswindowMap = function() {
  this.getWakelockswindowMap().clear();
  return this;};


/**
 * optional int32 relativeTime = 39;
 * @return {number}
 */
proto.stats.ResourceUsageStats.prototype.getRelativetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 39, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.ResourceUsageStats} returns this
 */
proto.stats.ResourceUsageStats.prototype.setRelativetime = function(value) {
  return jspb.Message.setProto3IntField(this, 39, value);
};


goog.object.extend(exports, proto.stats);
