// source: RunReport.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Instrumentation_pb = require('./Instrumentation_pb.js');
goog.object.extend(proto, Instrumentation_pb);
var Error_pb = require('./Error_pb.js');
goog.object.extend(proto, Error_pb);
var AtomicResult_pb = require('./AtomicResult_pb.js');
goog.object.extend(proto, AtomicResult_pb);
goog.exportSymbol('proto.tests.InstrumentationResult', null, global);
goog.exportSymbol('proto.tests.RunReport', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tests.RunReport = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tests.RunReport, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tests.RunReport.displayName = 'proto.tests.RunReport';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tests.InstrumentationResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tests.InstrumentationResult.repeatedFields_, null);
};
goog.inherits(proto.tests.InstrumentationResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tests.InstrumentationResult.displayName = 'proto.tests.InstrumentationResult';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tests.RunReport.prototype.toObject = function(opt_includeInstance) {
  return proto.tests.RunReport.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tests.RunReport} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.RunReport.toObject = function(includeInstance, msg) {
  var f, obj = {
    instrumentationresult: (f = msg.getInstrumentationresult()) && proto.tests.InstrumentationResult.toObject(includeInstance, f),
    runerror: (f = msg.getRunerror()) && Error_pb.Error.toObject(includeInstance, f),
    workkey: jspb.Message.getFieldWithDefault(msg, 3, ""),
    devicekey: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tests.RunReport}
 */
proto.tests.RunReport.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tests.RunReport;
  return proto.tests.RunReport.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tests.RunReport} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tests.RunReport}
 */
proto.tests.RunReport.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.tests.InstrumentationResult;
      reader.readMessage(value,proto.tests.InstrumentationResult.deserializeBinaryFromReader);
      msg.setInstrumentationresult(value);
      break;
    case 2:
      var value = new Error_pb.Error;
      reader.readMessage(value,Error_pb.Error.deserializeBinaryFromReader);
      msg.setRunerror(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkkey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDevicekey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tests.RunReport.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tests.RunReport.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tests.RunReport} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.RunReport.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInstrumentationresult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.tests.InstrumentationResult.serializeBinaryToWriter
    );
  }
  f = message.getRunerror();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      Error_pb.Error.serializeBinaryToWriter
    );
  }
  f = message.getWorkkey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDevicekey();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional InstrumentationResult instrumentationResult = 1;
 * @return {?proto.tests.InstrumentationResult}
 */
proto.tests.RunReport.prototype.getInstrumentationresult = function() {
  return /** @type{?proto.tests.InstrumentationResult} */ (
    jspb.Message.getWrapperField(this, proto.tests.InstrumentationResult, 1));
};


/**
 * @param {?proto.tests.InstrumentationResult|undefined} value
 * @return {!proto.tests.RunReport} returns this
*/
proto.tests.RunReport.prototype.setInstrumentationresult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tests.RunReport} returns this
 */
proto.tests.RunReport.prototype.clearInstrumentationresult = function() {
  return this.setInstrumentationresult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tests.RunReport.prototype.hasInstrumentationresult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Error runError = 2;
 * @return {?proto.tests.Error}
 */
proto.tests.RunReport.prototype.getRunerror = function() {
  return /** @type{?proto.tests.Error} */ (
    jspb.Message.getWrapperField(this, Error_pb.Error, 2));
};


/**
 * @param {?proto.tests.Error|undefined} value
 * @return {!proto.tests.RunReport} returns this
*/
proto.tests.RunReport.prototype.setRunerror = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tests.RunReport} returns this
 */
proto.tests.RunReport.prototype.clearRunerror = function() {
  return this.setRunerror(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tests.RunReport.prototype.hasRunerror = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string workKey = 3;
 * @return {string}
 */
proto.tests.RunReport.prototype.getWorkkey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.tests.RunReport} returns this
 */
proto.tests.RunReport.prototype.setWorkkey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string deviceKey = 4;
 * @return {string}
 */
proto.tests.RunReport.prototype.getDevicekey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.tests.RunReport} returns this
 */
proto.tests.RunReport.prototype.setDevicekey = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tests.InstrumentationResult.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tests.InstrumentationResult.prototype.toObject = function(opt_includeInstance) {
  return proto.tests.InstrumentationResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tests.InstrumentationResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.InstrumentationResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    instrumentation: (f = msg.getInstrumentation()) && Instrumentation_pb.Instrumentation.toObject(includeInstance, f),
    atomicresultsList: jspb.Message.toObjectList(msg.getAtomicresultsList(),
    AtomicResult_pb.AtomicResult.toObject, includeInstance),
    retriedatomicresultsList: jspb.Message.toObjectList(msg.getRetriedatomicresultsList(),
    AtomicResult_pb.AtomicResult.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tests.InstrumentationResult}
 */
proto.tests.InstrumentationResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tests.InstrumentationResult;
  return proto.tests.InstrumentationResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tests.InstrumentationResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tests.InstrumentationResult}
 */
proto.tests.InstrumentationResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Instrumentation_pb.Instrumentation;
      reader.readMessage(value,Instrumentation_pb.Instrumentation.deserializeBinaryFromReader);
      msg.setInstrumentation(value);
      break;
    case 2:
      var value = new AtomicResult_pb.AtomicResult;
      reader.readMessage(value,AtomicResult_pb.AtomicResult.deserializeBinaryFromReader);
      msg.addAtomicresults(value);
      break;
    case 3:
      var value = new AtomicResult_pb.AtomicResult;
      reader.readMessage(value,AtomicResult_pb.AtomicResult.deserializeBinaryFromReader);
      msg.addRetriedatomicresults(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tests.InstrumentationResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tests.InstrumentationResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tests.InstrumentationResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.InstrumentationResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInstrumentation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Instrumentation_pb.Instrumentation.serializeBinaryToWriter
    );
  }
  f = message.getAtomicresultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      AtomicResult_pb.AtomicResult.serializeBinaryToWriter
    );
  }
  f = message.getRetriedatomicresultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      AtomicResult_pb.AtomicResult.serializeBinaryToWriter
    );
  }
};


/**
 * optional Instrumentation instrumentation = 1;
 * @return {?proto.tests.Instrumentation}
 */
proto.tests.InstrumentationResult.prototype.getInstrumentation = function() {
  return /** @type{?proto.tests.Instrumentation} */ (
    jspb.Message.getWrapperField(this, Instrumentation_pb.Instrumentation, 1));
};


/**
 * @param {?proto.tests.Instrumentation|undefined} value
 * @return {!proto.tests.InstrumentationResult} returns this
*/
proto.tests.InstrumentationResult.prototype.setInstrumentation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.tests.InstrumentationResult} returns this
 */
proto.tests.InstrumentationResult.prototype.clearInstrumentation = function() {
  return this.setInstrumentation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.tests.InstrumentationResult.prototype.hasInstrumentation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated AtomicResult atomicResults = 2;
 * @return {!Array<!proto.tests.AtomicResult>}
 */
proto.tests.InstrumentationResult.prototype.getAtomicresultsList = function() {
  return /** @type{!Array<!proto.tests.AtomicResult>} */ (
    jspb.Message.getRepeatedWrapperField(this, AtomicResult_pb.AtomicResult, 2));
};


/**
 * @param {!Array<!proto.tests.AtomicResult>} value
 * @return {!proto.tests.InstrumentationResult} returns this
*/
proto.tests.InstrumentationResult.prototype.setAtomicresultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.tests.AtomicResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tests.AtomicResult}
 */
proto.tests.InstrumentationResult.prototype.addAtomicresults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.tests.AtomicResult, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tests.InstrumentationResult} returns this
 */
proto.tests.InstrumentationResult.prototype.clearAtomicresultsList = function() {
  return this.setAtomicresultsList([]);
};


/**
 * repeated AtomicResult retriedAtomicResults = 3;
 * @return {!Array<!proto.tests.AtomicResult>}
 */
proto.tests.InstrumentationResult.prototype.getRetriedatomicresultsList = function() {
  return /** @type{!Array<!proto.tests.AtomicResult>} */ (
    jspb.Message.getRepeatedWrapperField(this, AtomicResult_pb.AtomicResult, 3));
};


/**
 * @param {!Array<!proto.tests.AtomicResult>} value
 * @return {!proto.tests.InstrumentationResult} returns this
*/
proto.tests.InstrumentationResult.prototype.setRetriedatomicresultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.tests.AtomicResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tests.AtomicResult}
 */
proto.tests.InstrumentationResult.prototype.addRetriedatomicresults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.tests.AtomicResult, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tests.InstrumentationResult} returns this
 */
proto.tests.InstrumentationResult.prototype.clearRetriedatomicresultsList = function() {
  return this.setRetriedatomicresultsList([]);
};


goog.object.extend(exports, proto.tests);
