// source: StatsFrame.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var VmPropsStats_pb = require('./VmPropsStats_pb.js');
goog.object.extend(proto, VmPropsStats_pb);
var StorageStats_pb = require('./StorageStats_pb.js');
goog.object.extend(proto, StorageStats_pb);
var ProcessStats_pb = require('./ProcessStats_pb.js');
goog.object.extend(proto, ProcessStats_pb);
var MemoryStats_pb = require('./MemoryStats_pb.js');
goog.object.extend(proto, MemoryStats_pb);
var BinderStats_pb = require('./BinderStats_pb.js');
goog.object.extend(proto, BinderStats_pb);
var ThreadStats_pb = require('./ThreadStats_pb.js');
goog.object.extend(proto, ThreadStats_pb);
var GcStats_pb = require('./GcStats_pb.js');
goog.object.extend(proto, GcStats_pb);
var FrameStats_pb = require('./FrameStats_pb.js');
goog.object.extend(proto, FrameStats_pb);
var ApplicationStats_pb = require('./ApplicationStats_pb.js');
goog.object.extend(proto, ApplicationStats_pb);
var ActivityStats_pb = require('./ActivityStats_pb.js');
goog.object.extend(proto, ActivityStats_pb);
var FileIoStats_pb = require('./FileIoStats_pb.js');
goog.object.extend(proto, FileIoStats_pb);
var NetworkStats_pb = require('./NetworkStats_pb.js');
goog.object.extend(proto, NetworkStats_pb);
var UnixProcessStats_pb = require('./UnixProcessStats_pb.js');
goog.object.extend(proto, UnixProcessStats_pb);
var ResourceUsageStats_pb = require('./ResourceUsageStats_pb.js');
goog.object.extend(proto, ResourceUsageStats_pb);
goog.exportSymbol('proto.stats.StatsFrame', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.stats.StatsFrame = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.stats.StatsFrame.repeatedFields_, null);
};
goog.inherits(proto.stats.StatsFrame, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.stats.StatsFrame.displayName = 'proto.stats.StatsFrame';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.stats.StatsFrame.repeatedFields_ = [6,7,8,9,10,11,12,13,14,15,16];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.stats.StatsFrame.prototype.toObject = function(opt_includeInstance) {
  return proto.stats.StatsFrame.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.stats.StatsFrame} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.StatsFrame.toObject = function(includeInstance, msg) {
  var f, obj = {
    referencetime: jspb.Message.getFieldWithDefault(msg, 1, 0),
    vmpropsstats: (f = msg.getVmpropsstats()) && VmPropsStats_pb.VmPropsStats.toObject(includeInstance, f),
    processstats: (f = msg.getProcessstats()) && ProcessStats_pb.ProcessStats.toObject(includeInstance, f),
    startstoragestats: (f = msg.getStartstoragestats()) && StorageStats_pb.StorageStats.toObject(includeInstance, f),
    endstoragestats: (f = msg.getEndstoragestats()) && StorageStats_pb.StorageStats.toObject(includeInstance, f),
    memorystatsList: jspb.Message.toObjectList(msg.getMemorystatsList(),
    MemoryStats_pb.MemoryStats.toObject, includeInstance),
    binderstatsList: jspb.Message.toObjectList(msg.getBinderstatsList(),
    BinderStats_pb.BinderStats.toObject, includeInstance),
    threadstatsList: jspb.Message.toObjectList(msg.getThreadstatsList(),
    ThreadStats_pb.ThreadStats.toObject, includeInstance),
    gcstatsList: jspb.Message.toObjectList(msg.getGcstatsList(),
    GcStats_pb.GcStats.toObject, includeInstance),
    framestatsList: jspb.Message.toObjectList(msg.getFramestatsList(),
    FrameStats_pb.FrameStats.toObject, includeInstance),
    applicationstatsList: jspb.Message.toObjectList(msg.getApplicationstatsList(),
    ApplicationStats_pb.ApplicationStats.toObject, includeInstance),
    activitystatsList: jspb.Message.toObjectList(msg.getActivitystatsList(),
    ActivityStats_pb.ActivityStats.toObject, includeInstance),
    fileiostatsList: jspb.Message.toObjectList(msg.getFileiostatsList(),
    FileIoStats_pb.FileIoStats.toObject, includeInstance),
    networkstatsList: jspb.Message.toObjectList(msg.getNetworkstatsList(),
    NetworkStats_pb.NetworkStats.toObject, includeInstance),
    unixprocessstatsList: jspb.Message.toObjectList(msg.getUnixprocessstatsList(),
    UnixProcessStats_pb.UnixProcessStats.toObject, includeInstance),
    resourceusagestatsList: jspb.Message.toObjectList(msg.getResourceusagestatsList(),
    ResourceUsageStats_pb.ResourceUsageStats.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.stats.StatsFrame}
 */
proto.stats.StatsFrame.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.stats.StatsFrame;
  return proto.stats.StatsFrame.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.stats.StatsFrame} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.stats.StatsFrame}
 */
proto.stats.StatsFrame.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setReferencetime(value);
      break;
    case 2:
      var value = new VmPropsStats_pb.VmPropsStats;
      reader.readMessage(value,VmPropsStats_pb.VmPropsStats.deserializeBinaryFromReader);
      msg.setVmpropsstats(value);
      break;
    case 3:
      var value = new ProcessStats_pb.ProcessStats;
      reader.readMessage(value,ProcessStats_pb.ProcessStats.deserializeBinaryFromReader);
      msg.setProcessstats(value);
      break;
    case 4:
      var value = new StorageStats_pb.StorageStats;
      reader.readMessage(value,StorageStats_pb.StorageStats.deserializeBinaryFromReader);
      msg.setStartstoragestats(value);
      break;
    case 5:
      var value = new StorageStats_pb.StorageStats;
      reader.readMessage(value,StorageStats_pb.StorageStats.deserializeBinaryFromReader);
      msg.setEndstoragestats(value);
      break;
    case 6:
      var value = new MemoryStats_pb.MemoryStats;
      reader.readMessage(value,MemoryStats_pb.MemoryStats.deserializeBinaryFromReader);
      msg.addMemorystats(value);
      break;
    case 7:
      var value = new BinderStats_pb.BinderStats;
      reader.readMessage(value,BinderStats_pb.BinderStats.deserializeBinaryFromReader);
      msg.addBinderstats(value);
      break;
    case 8:
      var value = new ThreadStats_pb.ThreadStats;
      reader.readMessage(value,ThreadStats_pb.ThreadStats.deserializeBinaryFromReader);
      msg.addThreadstats(value);
      break;
    case 9:
      var value = new GcStats_pb.GcStats;
      reader.readMessage(value,GcStats_pb.GcStats.deserializeBinaryFromReader);
      msg.addGcstats(value);
      break;
    case 10:
      var value = new FrameStats_pb.FrameStats;
      reader.readMessage(value,FrameStats_pb.FrameStats.deserializeBinaryFromReader);
      msg.addFramestats(value);
      break;
    case 11:
      var value = new ApplicationStats_pb.ApplicationStats;
      reader.readMessage(value,ApplicationStats_pb.ApplicationStats.deserializeBinaryFromReader);
      msg.addApplicationstats(value);
      break;
    case 12:
      var value = new ActivityStats_pb.ActivityStats;
      reader.readMessage(value,ActivityStats_pb.ActivityStats.deserializeBinaryFromReader);
      msg.addActivitystats(value);
      break;
    case 13:
      var value = new FileIoStats_pb.FileIoStats;
      reader.readMessage(value,FileIoStats_pb.FileIoStats.deserializeBinaryFromReader);
      msg.addFileiostats(value);
      break;
    case 14:
      var value = new NetworkStats_pb.NetworkStats;
      reader.readMessage(value,NetworkStats_pb.NetworkStats.deserializeBinaryFromReader);
      msg.addNetworkstats(value);
      break;
    case 15:
      var value = new UnixProcessStats_pb.UnixProcessStats;
      reader.readMessage(value,UnixProcessStats_pb.UnixProcessStats.deserializeBinaryFromReader);
      msg.addUnixprocessstats(value);
      break;
    case 16:
      var value = new ResourceUsageStats_pb.ResourceUsageStats;
      reader.readMessage(value,ResourceUsageStats_pb.ResourceUsageStats.deserializeBinaryFromReader);
      msg.addResourceusagestats(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.stats.StatsFrame.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.stats.StatsFrame.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.stats.StatsFrame} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.stats.StatsFrame.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReferencetime();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getVmpropsstats();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      VmPropsStats_pb.VmPropsStats.serializeBinaryToWriter
    );
  }
  f = message.getProcessstats();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      ProcessStats_pb.ProcessStats.serializeBinaryToWriter
    );
  }
  f = message.getStartstoragestats();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      StorageStats_pb.StorageStats.serializeBinaryToWriter
    );
  }
  f = message.getEndstoragestats();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      StorageStats_pb.StorageStats.serializeBinaryToWriter
    );
  }
  f = message.getMemorystatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      MemoryStats_pb.MemoryStats.serializeBinaryToWriter
    );
  }
  f = message.getBinderstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      BinderStats_pb.BinderStats.serializeBinaryToWriter
    );
  }
  f = message.getThreadstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      ThreadStats_pb.ThreadStats.serializeBinaryToWriter
    );
  }
  f = message.getGcstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      GcStats_pb.GcStats.serializeBinaryToWriter
    );
  }
  f = message.getFramestatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      FrameStats_pb.FrameStats.serializeBinaryToWriter
    );
  }
  f = message.getApplicationstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      ApplicationStats_pb.ApplicationStats.serializeBinaryToWriter
    );
  }
  f = message.getActivitystatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      ActivityStats_pb.ActivityStats.serializeBinaryToWriter
    );
  }
  f = message.getFileiostatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      FileIoStats_pb.FileIoStats.serializeBinaryToWriter
    );
  }
  f = message.getNetworkstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      14,
      f,
      NetworkStats_pb.NetworkStats.serializeBinaryToWriter
    );
  }
  f = message.getUnixprocessstatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      UnixProcessStats_pb.UnixProcessStats.serializeBinaryToWriter
    );
  }
  f = message.getResourceusagestatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      16,
      f,
      ResourceUsageStats_pb.ResourceUsageStats.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 referenceTime = 1;
 * @return {number}
 */
proto.stats.StatsFrame.prototype.getReferencetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.setReferencetime = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional VmPropsStats vmPropsStats = 2;
 * @return {?proto.stats.VmPropsStats}
 */
proto.stats.StatsFrame.prototype.getVmpropsstats = function() {
  return /** @type{?proto.stats.VmPropsStats} */ (
    jspb.Message.getWrapperField(this, VmPropsStats_pb.VmPropsStats, 2));
};


/**
 * @param {?proto.stats.VmPropsStats|undefined} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setVmpropsstats = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearVmpropsstats = function() {
  return this.setVmpropsstats(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stats.StatsFrame.prototype.hasVmpropsstats = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ProcessStats processStats = 3;
 * @return {?proto.stats.ProcessStats}
 */
proto.stats.StatsFrame.prototype.getProcessstats = function() {
  return /** @type{?proto.stats.ProcessStats} */ (
    jspb.Message.getWrapperField(this, ProcessStats_pb.ProcessStats, 3));
};


/**
 * @param {?proto.stats.ProcessStats|undefined} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setProcessstats = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearProcessstats = function() {
  return this.setProcessstats(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stats.StatsFrame.prototype.hasProcessstats = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional StorageStats startStorageStats = 4;
 * @return {?proto.stats.StorageStats}
 */
proto.stats.StatsFrame.prototype.getStartstoragestats = function() {
  return /** @type{?proto.stats.StorageStats} */ (
    jspb.Message.getWrapperField(this, StorageStats_pb.StorageStats, 4));
};


/**
 * @param {?proto.stats.StorageStats|undefined} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setStartstoragestats = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearStartstoragestats = function() {
  return this.setStartstoragestats(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stats.StatsFrame.prototype.hasStartstoragestats = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional StorageStats endStorageStats = 5;
 * @return {?proto.stats.StorageStats}
 */
proto.stats.StatsFrame.prototype.getEndstoragestats = function() {
  return /** @type{?proto.stats.StorageStats} */ (
    jspb.Message.getWrapperField(this, StorageStats_pb.StorageStats, 5));
};


/**
 * @param {?proto.stats.StorageStats|undefined} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setEndstoragestats = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearEndstoragestats = function() {
  return this.setEndstoragestats(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.stats.StatsFrame.prototype.hasEndstoragestats = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated MemoryStats memoryStats = 6;
 * @return {!Array<!proto.stats.MemoryStats>}
 */
proto.stats.StatsFrame.prototype.getMemorystatsList = function() {
  return /** @type{!Array<!proto.stats.MemoryStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, MemoryStats_pb.MemoryStats, 6));
};


/**
 * @param {!Array<!proto.stats.MemoryStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setMemorystatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.stats.MemoryStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.MemoryStats}
 */
proto.stats.StatsFrame.prototype.addMemorystats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.stats.MemoryStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearMemorystatsList = function() {
  return this.setMemorystatsList([]);
};


/**
 * repeated BinderStats binderStats = 7;
 * @return {!Array<!proto.stats.BinderStats>}
 */
proto.stats.StatsFrame.prototype.getBinderstatsList = function() {
  return /** @type{!Array<!proto.stats.BinderStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, BinderStats_pb.BinderStats, 7));
};


/**
 * @param {!Array<!proto.stats.BinderStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setBinderstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.stats.BinderStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.BinderStats}
 */
proto.stats.StatsFrame.prototype.addBinderstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.stats.BinderStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearBinderstatsList = function() {
  return this.setBinderstatsList([]);
};


/**
 * repeated ThreadStats threadStats = 8;
 * @return {!Array<!proto.stats.ThreadStats>}
 */
proto.stats.StatsFrame.prototype.getThreadstatsList = function() {
  return /** @type{!Array<!proto.stats.ThreadStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, ThreadStats_pb.ThreadStats, 8));
};


/**
 * @param {!Array<!proto.stats.ThreadStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setThreadstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.stats.ThreadStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.ThreadStats}
 */
proto.stats.StatsFrame.prototype.addThreadstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.stats.ThreadStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearThreadstatsList = function() {
  return this.setThreadstatsList([]);
};


/**
 * repeated GcStats gcStats = 9;
 * @return {!Array<!proto.stats.GcStats>}
 */
proto.stats.StatsFrame.prototype.getGcstatsList = function() {
  return /** @type{!Array<!proto.stats.GcStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, GcStats_pb.GcStats, 9));
};


/**
 * @param {!Array<!proto.stats.GcStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setGcstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.stats.GcStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.GcStats}
 */
proto.stats.StatsFrame.prototype.addGcstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.stats.GcStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearGcstatsList = function() {
  return this.setGcstatsList([]);
};


/**
 * repeated FrameStats frameStats = 10;
 * @return {!Array<!proto.stats.FrameStats>}
 */
proto.stats.StatsFrame.prototype.getFramestatsList = function() {
  return /** @type{!Array<!proto.stats.FrameStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, FrameStats_pb.FrameStats, 10));
};


/**
 * @param {!Array<!proto.stats.FrameStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setFramestatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.stats.FrameStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.FrameStats}
 */
proto.stats.StatsFrame.prototype.addFramestats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.stats.FrameStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearFramestatsList = function() {
  return this.setFramestatsList([]);
};


/**
 * repeated ApplicationStats applicationStats = 11;
 * @return {!Array<!proto.stats.ApplicationStats>}
 */
proto.stats.StatsFrame.prototype.getApplicationstatsList = function() {
  return /** @type{!Array<!proto.stats.ApplicationStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, ApplicationStats_pb.ApplicationStats, 11));
};


/**
 * @param {!Array<!proto.stats.ApplicationStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setApplicationstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.stats.ApplicationStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.ApplicationStats}
 */
proto.stats.StatsFrame.prototype.addApplicationstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.stats.ApplicationStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearApplicationstatsList = function() {
  return this.setApplicationstatsList([]);
};


/**
 * repeated ActivityStats activityStats = 12;
 * @return {!Array<!proto.stats.ActivityStats>}
 */
proto.stats.StatsFrame.prototype.getActivitystatsList = function() {
  return /** @type{!Array<!proto.stats.ActivityStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, ActivityStats_pb.ActivityStats, 12));
};


/**
 * @param {!Array<!proto.stats.ActivityStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setActivitystatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.stats.ActivityStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.ActivityStats}
 */
proto.stats.StatsFrame.prototype.addActivitystats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.stats.ActivityStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearActivitystatsList = function() {
  return this.setActivitystatsList([]);
};


/**
 * repeated FileIoStats fileIoStats = 13;
 * @return {!Array<!proto.stats.FileIoStats>}
 */
proto.stats.StatsFrame.prototype.getFileiostatsList = function() {
  return /** @type{!Array<!proto.stats.FileIoStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, FileIoStats_pb.FileIoStats, 13));
};


/**
 * @param {!Array<!proto.stats.FileIoStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setFileiostatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.stats.FileIoStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.FileIoStats}
 */
proto.stats.StatsFrame.prototype.addFileiostats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.stats.FileIoStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearFileiostatsList = function() {
  return this.setFileiostatsList([]);
};


/**
 * repeated NetworkStats networkStats = 14;
 * @return {!Array<!proto.stats.NetworkStats>}
 */
proto.stats.StatsFrame.prototype.getNetworkstatsList = function() {
  return /** @type{!Array<!proto.stats.NetworkStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, NetworkStats_pb.NetworkStats, 14));
};


/**
 * @param {!Array<!proto.stats.NetworkStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setNetworkstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 14, value);
};


/**
 * @param {!proto.stats.NetworkStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.NetworkStats}
 */
proto.stats.StatsFrame.prototype.addNetworkstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 14, opt_value, proto.stats.NetworkStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearNetworkstatsList = function() {
  return this.setNetworkstatsList([]);
};


/**
 * repeated UnixProcessStats unixProcessStats = 15;
 * @return {!Array<!proto.stats.UnixProcessStats>}
 */
proto.stats.StatsFrame.prototype.getUnixprocessstatsList = function() {
  return /** @type{!Array<!proto.stats.UnixProcessStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, UnixProcessStats_pb.UnixProcessStats, 15));
};


/**
 * @param {!Array<!proto.stats.UnixProcessStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setUnixprocessstatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.stats.UnixProcessStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.UnixProcessStats}
 */
proto.stats.StatsFrame.prototype.addUnixprocessstats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.stats.UnixProcessStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearUnixprocessstatsList = function() {
  return this.setUnixprocessstatsList([]);
};


/**
 * repeated ResourceUsageStats resourceUsageStats = 16;
 * @return {!Array<!proto.stats.ResourceUsageStats>}
 */
proto.stats.StatsFrame.prototype.getResourceusagestatsList = function() {
  return /** @type{!Array<!proto.stats.ResourceUsageStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, ResourceUsageStats_pb.ResourceUsageStats, 16));
};


/**
 * @param {!Array<!proto.stats.ResourceUsageStats>} value
 * @return {!proto.stats.StatsFrame} returns this
*/
proto.stats.StatsFrame.prototype.setResourceusagestatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 16, value);
};


/**
 * @param {!proto.stats.ResourceUsageStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.stats.ResourceUsageStats}
 */
proto.stats.StatsFrame.prototype.addResourceusagestats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 16, opt_value, proto.stats.ResourceUsageStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.stats.StatsFrame} returns this
 */
proto.stats.StatsFrame.prototype.clearResourceusagestatsList = function() {
  return this.setResourceusagestatsList([]);
};


goog.object.extend(exports, proto.stats);
