// source: TestSummaryProfile.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.tests.LifecycleProfile', null, global);
goog.exportSymbol('proto.tests.TestSummaryProfile', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tests.TestSummaryProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.tests.TestSummaryProfile.repeatedFields_, null);
};
goog.inherits(proto.tests.TestSummaryProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tests.TestSummaryProfile.displayName = 'proto.tests.TestSummaryProfile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tests.LifecycleProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tests.LifecycleProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tests.LifecycleProfile.displayName = 'proto.tests.LifecycleProfile';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.tests.TestSummaryProfile.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tests.TestSummaryProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.tests.TestSummaryProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tests.TestSummaryProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.TestSummaryProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    timetocallapponcreate: jspb.Message.getFieldWithDefault(msg, 1, 0),
    apponcreatetime: jspb.Message.getFieldWithDefault(msg, 2, 0),
    timetofirstactivityoncreate: jspb.Message.getFieldWithDefault(msg, 3, 0),
    timetofirstactivityonstart: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timetofirstactivityonresume: jspb.Message.getFieldWithDefault(msg, 5, 0),
    batterytemperaturedelta: jspb.Message.getFieldWithDefault(msg, 6, 0),
    batteryleveldelta: jspb.Message.getFieldWithDefault(msg, 7, 0),
    activityoncreateprofilesList: jspb.Message.toObjectList(msg.getActivityoncreateprofilesList(),
    proto.tests.LifecycleProfile.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tests.TestSummaryProfile}
 */
proto.tests.TestSummaryProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tests.TestSummaryProfile;
  return proto.tests.TestSummaryProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tests.TestSummaryProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tests.TestSummaryProfile}
 */
proto.tests.TestSummaryProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimetocallapponcreate(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setApponcreatetime(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimetofirstactivityoncreate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimetofirstactivityonstart(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimetofirstactivityonresume(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBatterytemperaturedelta(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBatteryleveldelta(value);
      break;
    case 8:
      var value = new proto.tests.LifecycleProfile;
      reader.readMessage(value,proto.tests.LifecycleProfile.deserializeBinaryFromReader);
      msg.addActivityoncreateprofiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tests.TestSummaryProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tests.TestSummaryProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tests.TestSummaryProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.TestSummaryProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimetocallapponcreate();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getApponcreatetime();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTimetofirstactivityoncreate();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTimetofirstactivityonstart();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getTimetofirstactivityonresume();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getBatterytemperaturedelta();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getBatteryleveldelta();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getActivityoncreateprofilesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.tests.LifecycleProfile.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 timeToCallAppOnCreate = 1;
 * @return {number}
 */
proto.tests.TestSummaryProfile.prototype.getTimetocallapponcreate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.setTimetocallapponcreate = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 appOnCreateTime = 2;
 * @return {number}
 */
proto.tests.TestSummaryProfile.prototype.getApponcreatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.setApponcreatetime = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 timeToFirstActivityOnCreate = 3;
 * @return {number}
 */
proto.tests.TestSummaryProfile.prototype.getTimetofirstactivityoncreate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.setTimetofirstactivityoncreate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 timeToFirstActivityOnStart = 4;
 * @return {number}
 */
proto.tests.TestSummaryProfile.prototype.getTimetofirstactivityonstart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.setTimetofirstactivityonstart = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 timeToFirstActivityOnResume = 5;
 * @return {number}
 */
proto.tests.TestSummaryProfile.prototype.getTimetofirstactivityonresume = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.setTimetofirstactivityonresume = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 batteryTemperatureDelta = 6;
 * @return {number}
 */
proto.tests.TestSummaryProfile.prototype.getBatterytemperaturedelta = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.setBatterytemperaturedelta = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 batteryLevelDelta = 7;
 * @return {number}
 */
proto.tests.TestSummaryProfile.prototype.getBatteryleveldelta = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.setBatteryleveldelta = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * repeated LifecycleProfile activityOnCreateProfiles = 8;
 * @return {!Array<!proto.tests.LifecycleProfile>}
 */
proto.tests.TestSummaryProfile.prototype.getActivityoncreateprofilesList = function() {
  return /** @type{!Array<!proto.tests.LifecycleProfile>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.tests.LifecycleProfile, 8));
};


/**
 * @param {!Array<!proto.tests.LifecycleProfile>} value
 * @return {!proto.tests.TestSummaryProfile} returns this
*/
proto.tests.TestSummaryProfile.prototype.setActivityoncreateprofilesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.tests.LifecycleProfile=} opt_value
 * @param {number=} opt_index
 * @return {!proto.tests.LifecycleProfile}
 */
proto.tests.TestSummaryProfile.prototype.addActivityoncreateprofiles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.tests.LifecycleProfile, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.tests.TestSummaryProfile} returns this
 */
proto.tests.TestSummaryProfile.prototype.clearActivityoncreateprofilesList = function() {
  return this.setActivityoncreateprofilesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tests.LifecycleProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.tests.LifecycleProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tests.LifecycleProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.LifecycleProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timetaken: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tests.LifecycleProfile}
 */
proto.tests.LifecycleProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tests.LifecycleProfile;
  return proto.tests.LifecycleProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tests.LifecycleProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tests.LifecycleProfile}
 */
proto.tests.LifecycleProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimetaken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tests.LifecycleProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tests.LifecycleProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tests.LifecycleProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tests.LifecycleProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimetaken();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.tests.LifecycleProfile.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tests.LifecycleProfile} returns this
 */
proto.tests.LifecycleProfile.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 timeTaken = 2;
 * @return {number}
 */
proto.tests.LifecycleProfile.prototype.getTimetaken = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.tests.LifecycleProfile} returns this
 */
proto.tests.LifecycleProfile.prototype.setTimetaken = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


goog.object.extend(exports, proto.tests);
