// source: Timeline.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.reports.TimelineEntry', null, global);
goog.exportSymbol('proto.reports.TimelineSection', null, global);
goog.exportSymbol('proto.reports.TimelineType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reports.TimelineSection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.reports.TimelineSection.repeatedFields_, null);
};
goog.inherits(proto.reports.TimelineSection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reports.TimelineSection.displayName = 'proto.reports.TimelineSection';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.reports.TimelineEntry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.reports.TimelineEntry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.reports.TimelineEntry.displayName = 'proto.reports.TimelineEntry';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.reports.TimelineSection.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reports.TimelineSection.prototype.toObject = function(opt_includeInstance) {
  return proto.reports.TimelineSection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reports.TimelineSection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reports.TimelineSection.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    iconname: jspb.Message.getFieldWithDefault(msg, 2, ""),
    relativestarttime: jspb.Message.getFieldWithDefault(msg, 3, 0),
    relativeendtime: jspb.Message.getFieldWithDefault(msg, 4, 0),
    entriesList: jspb.Message.toObjectList(msg.getEntriesList(),
    proto.reports.TimelineEntry.toObject, includeInstance),
    logfilepos: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reports.TimelineSection}
 */
proto.reports.TimelineSection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reports.TimelineSection;
  return proto.reports.TimelineSection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reports.TimelineSection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reports.TimelineSection}
 */
proto.reports.TimelineSection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIconname(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRelativestarttime(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRelativeendtime(value);
      break;
    case 5:
      var value = new proto.reports.TimelineEntry;
      reader.readMessage(value,proto.reports.TimelineEntry.deserializeBinaryFromReader);
      msg.addEntries(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLogfilepos(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reports.TimelineSection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reports.TimelineSection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reports.TimelineSection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reports.TimelineSection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIconname();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRelativestarttime();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getRelativeendtime();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getEntriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.reports.TimelineEntry.serializeBinaryToWriter
    );
  }
  f = message.getLogfilepos();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.reports.TimelineSection.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.reports.TimelineSection} returns this
 */
proto.reports.TimelineSection.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string iconName = 2;
 * @return {string}
 */
proto.reports.TimelineSection.prototype.getIconname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.reports.TimelineSection} returns this
 */
proto.reports.TimelineSection.prototype.setIconname = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 relativeStartTime = 3;
 * @return {number}
 */
proto.reports.TimelineSection.prototype.getRelativestarttime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.reports.TimelineSection} returns this
 */
proto.reports.TimelineSection.prototype.setRelativestarttime = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 relativeEndTime = 4;
 * @return {number}
 */
proto.reports.TimelineSection.prototype.getRelativeendtime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.reports.TimelineSection} returns this
 */
proto.reports.TimelineSection.prototype.setRelativeendtime = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated TimelineEntry entries = 5;
 * @return {!Array<!proto.reports.TimelineEntry>}
 */
proto.reports.TimelineSection.prototype.getEntriesList = function() {
  return /** @type{!Array<!proto.reports.TimelineEntry>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.reports.TimelineEntry, 5));
};


/**
 * @param {!Array<!proto.reports.TimelineEntry>} value
 * @return {!proto.reports.TimelineSection} returns this
*/
proto.reports.TimelineSection.prototype.setEntriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.reports.TimelineEntry=} opt_value
 * @param {number=} opt_index
 * @return {!proto.reports.TimelineEntry}
 */
proto.reports.TimelineSection.prototype.addEntries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.reports.TimelineEntry, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.reports.TimelineSection} returns this
 */
proto.reports.TimelineSection.prototype.clearEntriesList = function() {
  return this.setEntriesList([]);
};


/**
 * optional int64 logFilePos = 6;
 * @return {number}
 */
proto.reports.TimelineSection.prototype.getLogfilepos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.reports.TimelineSection} returns this
 */
proto.reports.TimelineSection.prototype.setLogfilepos = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.reports.TimelineEntry.prototype.toObject = function(opt_includeInstance) {
  return proto.reports.TimelineEntry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.reports.TimelineEntry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reports.TimelineEntry.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.reports.TimelineEntry}
 */
proto.reports.TimelineEntry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.reports.TimelineEntry;
  return proto.reports.TimelineEntry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.reports.TimelineEntry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.reports.TimelineEntry}
 */
proto.reports.TimelineEntry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = /** @type {!proto.reports.TimelineType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.reports.TimelineEntry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.reports.TimelineEntry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.reports.TimelineEntry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.reports.TimelineEntry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.reports.TimelineEntry.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.reports.TimelineEntry} returns this
 */
proto.reports.TimelineEntry.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional TimelineType type = 2;
 * @return {!proto.reports.TimelineType}
 */
proto.reports.TimelineEntry.prototype.getType = function() {
  return /** @type {!proto.reports.TimelineType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.reports.TimelineType} value
 * @return {!proto.reports.TimelineEntry} returns this
 */
proto.reports.TimelineEntry.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.reports.TimelineType = {
  LOG: 0,
  STATS: 1
};

goog.object.extend(exports, proto.reports);
