package com.fluentbuild.apollo.runner

private const val PACKAGE_PREFIX = "com.fluentbuild.apollo."

const val ARG_TESTS_COUNT = "${PACKAGE_PREFIX}ARG_TESTS_COUNT"
const val ARG_OBSCURE_WINDOW_ENABLED = "${PACKAGE_PREFIX}ARG_OBSCURE_WINDOW_ENABLED"
const val ARG_AUTO_SCREEN_SHOT_ENABLED = "${PACKAGE_PREFIX}ARG_AUTO_SCREEN_SHOT_ENABLED"
const val ARG_RETRIEVE_TEST_FILES = "${PACKAGE_PREFIX}ARG_RETRIEVE_TEST_FILES"
const val ARG_RETRIEVE_APP_FILES = "${PACKAGE_PREFIX}ARG_RETRIEVE_APP_FILES"
const val ARG_CLEAR_DATA = "${PACKAGE_PREFIX}ARG_CLEAR_DATA"
const val ARG_PROFILER_SAMPLE_FREQUENCY = "${PACKAGE_PREFIX}ARG_PROFILER_SAMPLE_FREQUENCY"
const val ARG_AUTO_SCREEN_SHOT_FPS = "${PACKAGE_PREFIX}ARG_AUTO_SCREEN_SHOT_FPS"
const val ARG_AUTO_SCREEN_QUALITY = "${PACKAGE_PREFIX}ARG_AUTO_SCREEN_QUALITY"

const val JUNIT_TESTS_SEPARATOR = ","
const val ARG_JUNIT_TESTS_CLASS = "class"

const val ACTION_CANCEL_SIGNAL = "${PACKAGE_PREFIX}ACTION_CANCEL_SIGNAL"